# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Sandbox check: a file listing taken inside the rollout, compared to SolSwarm's own.

The authoritative check is PROBE_SOURCE + diff_trees, run once per job.
PROBE_SOURCE is a listing script that runs inside the first
rollout's sandbox after the agent exits and records every file path
visible there. diff_trees compares that listing by set equality against a
reference listing generated by running SolSwarm's entrypoint
(solswarm_container.reference_tree).

``collect``/``fingerprint`` are the PRE-FLIGHT inventory of what the server
hands the sandbox (problem files, staged skills, env names) — written once per
distinct input set before any rollout runs. They measure our inputs, not the
model's view; do not use them as a parity signal.

Values of environment variables are never recorded — only their names, since
the agent env carries auth tokens.
"""

import hashlib
import json
import logging
import os
from pathlib import Path
from typing import Any, Optional


LOG = logging.getLogger(__name__)

# Env vars whose PRESENCE affects how the sandbox is assembled (names only, never values).
_ENV_PREFIXES = ("SOLSWARM_", "CUDAGYM_", "OPENCODE_", "KF_", "XDG_")
_ENV_EXACT = ("PROBLEM_DIR", "PLATFORM_API_ENDPOINT", "NO_UPDATE_NOTIFIER")

# Walk bounds: the sandbox is small, but a runaway agent can make it big.
_MAX_ENTRIES = 400
_MAX_DEPTH = 3
# The OpenCode session db (large, binary, changes every turn) is session
# state, not a staged input.
_SKIP_DIRS = {".opencode-data", "__pycache__", ".git"}


def _tree(root: Path, max_entries: int = _MAX_ENTRIES, max_depth: int = _MAX_DEPTH) -> list[str]:
    """Sorted ``relative/path (size)`` lines for the files under ``root``."""
    if not root.is_dir():
        return []
    entries: list[str] = []
    truncated = False
    for dirpath, dirnames, filenames in os.walk(root):
        rel_dir = Path(dirpath).relative_to(root)
        if len(rel_dir.parts) >= max_depth:
            dirnames[:] = []
        dirnames[:] = sorted(d for d in dirnames if d not in _SKIP_DIRS)
        for name in sorted(filenames):
            if len(entries) >= max_entries:
                truncated = True
                break
            path = Path(dirpath) / name
            try:
                size = path.stat().st_size
            except OSError:
                size = -1
            entries.append(f"{(rel_dir / name).as_posix()} ({size}B)")
        if truncated:
            break
    if truncated:
        entries.append(f"...[truncated at {max_entries} entries]")
    return entries


def _skills(skills_dir: Optional[Path]) -> dict[str, Any]:
    """Names of the staged skills, flagging any that lack a SKILL.md."""
    if skills_dir is None or not Path(skills_dir).is_dir():
        return {"dir": str(skills_dir) if skills_dir else None, "count": 0, "names": [], "malformed": []}
    names, malformed = [], []
    for child in sorted(Path(skills_dir).iterdir()):
        if not child.is_dir():
            continue
        names.append(child.name)
        if not (child / "SKILL.md").is_file():
            malformed.append(child.name)
    return {"dir": str(skills_dir), "count": len(names), "names": names, "malformed": malformed}


def collect(
    work_dir: Path,
    *,
    skills_dir: Optional[Path] = None,
    env: Optional[dict[str, str]] = None,
    opencode_config: Optional[dict[str, Any]] = None,
    extra: Optional[dict[str, Any]] = None,
) -> dict[str, Any]:
    """Snapshot the inputs staged for the sandbox. Never raises — a manifest is diagnostics."""
    manifest: dict[str, Any] = {}
    try:
        work_dir = Path(work_dir)
        manifest = {
            # What the sandbox receives: workspace tree, problem files, staged skills.
            "workspace": {"dir": str(work_dir), "tree": _tree(work_dir)},
            "problem": {"files": _tree(work_dir / "problem", max_entries=50, max_depth=2)},
            "skills": _skills(skills_dir),
            # Config KEYS only: the opencode config carries the policy api key.
            "opencode_config_keys": sorted((opencode_config or {}).keys()),
            # Sandbox-shaping env NAMES only; values may carry auth tokens.
            "env_keys": sorted(k for k in (env or {}) if k.startswith(_ENV_PREFIXES) or k in _ENV_EXACT),
        }
        # Caller-supplied mode flags ride along verbatim.
        if extra:
            manifest.update(extra)
    except Exception as e:  # pragma: no cover - diagnostics must not break rollouts
        LOG.warning("sandbox manifest collection failed: %s", e)
        manifest = {"error": str(e)}
    return manifest


def digest(manifest: dict[str, Any]) -> str:
    """Stable short hash over the sandbox-defining parts of a manifest.

    Excludes per-rollout paths (every workspace has a fresh uuid dir), so two
    rollouts staged from the same inputs share a digest and drift stands out.
    """
    try:
        material = {
            "skills": manifest.get("skills", {}).get("names", []),
            "problem": [line.split(" (")[0] for line in manifest.get("problem", {}).get("files", [])],
            "env_keys": manifest.get("env_keys", []),
            "opencode_config_keys": manifest.get("opencode_config_keys", []),
        }
        return hashlib.sha256(json.dumps(material, sort_keys=True).encode()).hexdigest()[:12]
    except Exception:  # pragma: no cover - diagnostics must not break rollouts
        return "unknown"


def fingerprint(manifest: dict[str, Any]) -> dict[str, Any]:
    """Compact summary: counts, the digest, and the drift signals."""
    skills = manifest.get("skills", {})
    return {
        "digest": digest(manifest),
        "n_skills": skills.get("count", 0),
        "malformed_skills": skills.get("malformed", []),
        "n_problem_files": len(manifest.get("problem", {}).get("files", [])),
    }


# Job bind mounts that can be hidden (over-mounted with an empty directory)
# with no preparation. `/opt/nemo-rl` is NOT here because the cudagym CLI the
# agent must call is an editable install rooted in that tree — over-mounting
# it yields "No module named 'cudagym'". The agent adds /opt/nemo-rl to the
# hide list dynamically once a staged package copy is on PYTHONPATH
# (app._stage_cudagym_cli).
HIDEABLE_JOB_MOUNTS = ("/cluster_workspace", "/datasets", "/models", "/opt/gym_venvs")


def render(manifest: dict[str, Any]) -> str:
    """Human-readable manifest for the server log (logged once per process)."""
    lines = ["sandbox manifest:", f"  digest: {digest(manifest)}"]
    skills = manifest.get("skills", {})
    lines.append(f"  skills ({skills.get('count', 0)}): {', '.join(skills.get('names', [])) or '-'}")
    if skills.get("malformed"):
        lines.append(f"  skills MISSING SKILL.md: {', '.join(skills['malformed'])}")
    lines.append(f"  problem files: {', '.join(manifest.get('problem', {}).get('files', [])) or '-'}")
    lines.append(f"  env keys: {', '.join(manifest.get('env_keys', [])) or '-'}")
    lines.append(f"  opencode config keys: {', '.join(manifest.get('opencode_config_keys', [])) or '-'}")
    lines.append("  workspace tree:")
    lines.extend(f"    {line}" for line in manifest.get("workspace", {}).get("tree", []))
    return "\n".join(lines)


# --- the in-sandbox listing script (PROBE_SOURCE) ---------------------------
# Everything above inspects paths from the SERVER process, which is not what
# the model sees: with a mount namespace the model's filesystem view diverges
# from the server's, and in container mode SolSwarm's entrypoint assembles the
# sandbox entirely on its own -- a server-side inventory measures the wrong
# thing. PROBE_SOURCE therefore runs INSIDE the rollout (after the agent
# exits, so it sees the finished sandbox) and reports what was actually
# there: real paths, real skills, real tools, and whether the hidden mounts
# are really empty.
PROBE_SOURCE = r"""
# Raw, UNINTERPRETED snapshot of the sandbox, taken from inside the rollout.
#
# Deliberately semantics-free: it records WHAT IS THERE, not whether expected
# things are in expected places. A script that looks up /workspace and
# "skills" bakes in today's layout, so an upstream move would read as a failure
# instead of a difference. The listing is compared by EQUALITY against a
# reference listing produced by SolSwarm's own entrypoint at the pinned commit,
# so parity is a diff between two observed listings rather than a checklist of
# assumptions.
import json, os, subprocess, sys

# Roots to walk. "/" is walked shallowly so a NEW top-level directory shows up;
# the sandbox-owned roots are walked deeper. Nothing here asserts they exist.
SHALLOW = ["/"]
DEEP = ["/workspace", "/tmp", "/home", "/skills-library", "/skills-library-compat", "/prompts"]
# Walked 2 deep only: these are large READ-ONLY libraries (/context alone is
# ~14k files) whose presence and top-level layout matter, not every leaf -- and
# a full walk would blow the limit and truncate everything else.
MEDIUM = ["/context"]
# The job mounts. Walked 1 deep on purpose: enough to tell POPULATED from
# EMPTY, which is exactly what proves hiding worked, without dragging the
# training repo's file list into the diff.
MOUNTS = ["/opt/nemo-rl", "/opt/gym_venvs", "/datasets", "/cluster_workspace", "/models"]
SKIP = {".git", "__pycache__", "node_modules", ".opencode-data", "proc", "sys", "dev", "run"}
LIMIT = 20000

def walk(root, max_depth, out):
    if not os.path.exists(root):
        return
    base_depth = root.rstrip("/").count("/")
    for dirpath, dirnames, filenames in os.walk(root, onerror=lambda e: None):
        dirnames[:] = sorted(d for d in dirnames if d not in SKIP)
        depth = dirpath.rstrip("/").count("/") - base_depth
        if depth >= max_depth:
            dirnames[:] = []
        for name in sorted(dirnames):
            out.add(os.path.join(dirpath, name) + "/")
        for name in sorted(filenames):
            path = os.path.join(dirpath, name)
            try:
                out.add(f"{path}\t{os.path.getsize(path)}")
            except OSError:
                out.add(f"{path}\t?")
            if len(out) >= LIMIT:
                return

tree = set()
for r in SHALLOW:
    walk(r, 1, tree)
for r in DEEP:
    walk(r, 6, tree)
for r in MEDIUM:
    walk(r, 2, tree)
for r in MOUNTS:
    walk(r, 1, tree)

def _entrypoint_config_keys():
    # Top-level keys of the OpenCode config. Best effort: scan the entrypoint's
    # transcript for a config dump first; the pinned solswarm entrypoint does
    # not currently print one, so this usually falls back to the value this
    # process inherited from the agent server and labels it as ours.
    import glob
    for path in glob.glob("/mnt/solswarm-rollout/entrypoint.log"):
        try:
            for line in open(path, errors="replace"):
                if "OPENCODE_CONFIG_CONTENT" in line and "{" in line:
                    blob = line[line.index("{"):].strip()
                    return sorted(json.loads(blob).keys())
        except Exception:
            pass
    raw = os.environ.get("OPENCODE_CONFIG_CONTENT", "")
    if raw.startswith("{"):
        try:
            return sorted(json.loads(raw).keys()) + ["(ours, not the entrypoint's)"]
        except Exception:
            pass
    return []


def tool(cmd):
    try:
        r = subprocess.run(cmd, capture_output=True, text=True, timeout=30)
        return (r.stdout or r.stderr).strip().splitlines()[-1][:120] if r.returncode == 0 else f"FAILED rc={r.returncode}"
    except Exception as e:
        return f"FAILED {type(e).__name__}"

print(json.dumps({
    "probe": "in-sandbox-raw",
    # Facts about the process, not judgements about the layout.
    "cwd": os.getcwd(),
    "uid": os.getuid(),
    "home": os.environ.get("HOME", ""),
    "tree": sorted(tree),
    "truncated": len(tree) >= LIMIT,
    "tools": {
        "opencode": tool(["opencode", "--version"]),
        "cudagym": tool(["cudagym", "--help"])[:40],
        "cudagym_import": tool([sys.executable, "-c", "import cudagym;print(cudagym.__file__)"]),
        # entrypoint.sh is jq-dependent throughout: without jq the OpenCode
        # config comes out empty and the agent silently runs with defaults.
        "jq": tool(["jq", "--version"]),
        "curl": tool(["curl", "--version"]),
        "node": tool(["node", "--version"]),
        # Record that it RUNS, not what it printed: uuidgen emits a fresh value
        # every call, which would make this differ on every comparison.
        "uuidgen": "ok" if not tool(["uuidgen"]).startswith("FAILED") else "FAILED",
    },
    # Names only -- the agent env carries auth tokens.
    "env_keys": sorted(k for k in os.environ if k.startswith(("SOLSWARM_", "CUDAGYM_", "OPENCODE_", "KF_", "XDG_"))
                       or k in ("PROBLEM_DIR", "PLATFORM_API_ENDPOINT", "HOME", "PYTHONPATH")),
    # The entrypoint EXPORTS its own OPENCODE_CONFIG_CONTENT in a child shell,
    # so this process (its sibling) only ever sees what WE set -- a comparison
    # of the inherited value would structurally always agree. Prefer the config
    # the entrypoint actually handed OpenCode when its transcript contains one,
    # and label the fallback explicitly.
    "opencode_config_keys": _entrypoint_config_keys(),
}, indent=2))
"""


# --- tree equality ----------------------------------------------------------

# Roots the agent may write to during a normal session. Files appearing under
# them are its work product, not a change to the sandbox it was given.
MODEL_WRITABLE_ROOTS = ("/workspace", "/tmp", "/home/agent", "/traces", "/artifacts")

# Path fragments that legitimately differ run-to-run (uuids, pids, timestamps,
# the model's own work) and would swamp a diff; entries containing them are
# dropped before comparison. Everything else is compared verbatim.
_VOLATILE = (
    "/traces/session-",
    "/tmp/trace-upload.",
    "/tmp/.solswarm-trace-dir",
    "/tmp/optimizer-resolved.md",
    "/tmp/runtime-prompt.md",
    "/artifacts/",
    "/workspace/",  # the agent's own files are the point of the run
    "/home/agent/.local/",  # opencode session store
    "/home/agent/.cache/",
    # OpenCode's npm/plugin state is deliberately NOT excluded: the reference
    # is instead given long enough to install the same plugin
    # (solswarm_container.REFERENCE_SETTLE_SECONDS), so later additions under
    # those paths stay visible.
    "/traces/.trace-uploaded",  # written only when the trace POST succeeds
    "/tmp/.",  # JIT/compile temporaries from a working agent
    "/mnt/solswarm-rollout",  # our staging handle
    "sandbox_probe",  # the listing script's own artifacts
    "entrypoint.log",
)


def normalize_tree(tree: list[str]) -> set[str]:
    """A comparable path set: volatile entries removed, file sizes dropped.

    Sizes are dropped because a reference run and a training run legitimately
    differ in file CONTENT (different problem, different prompt) while the
    sandbox STRUCTURE must match.
    """
    out = set()
    for entry in tree:
        path = entry.split("\t", 1)[0]
        if any(v in path for v in _VOLATILE):
            continue
        out.add(path)
    return out


def diff_trees(reference: dict[str, Any], observed: dict[str, Any]) -> dict[str, Any]:
    """Equality check between SolSwarm's own sandbox and the RL sandbox.

    ``reference`` is a file listing taken from a sandbox built by SolSwarm's
    entrypoint with no RL wiring; ``observed`` is a listing from a training
    rollout. Both are raw trees, so this reports what the RL environment
    actually adds or removes rather than whether a hand-written expectation
    was met.
    """
    # Comparable path sets: volatile entries and file sizes dropped.
    ref = normalize_tree(reference.get("tree", []))
    obs = normalize_tree(observed.get("tree", []))
    missing, extra = sorted(ref - obs), sorted(obs - ref)
    # The two directions mean different things. MISSING is always a defect: the
    # environment lacks something SolSwarm provides. EXTRA is usually the model
    # doing its job -- it may write anywhere it can reach (scratch files like
    # /tmp/solution.py are normal work product). Only an extra path OUTSIDE the
    # model-writable roots indicates the environment itself gained something.
    unexpected = [p for p in extra if not p.startswith(MODEL_WRITABLE_ROOTS)]
    report = {
        "missing_in_rl": missing,
        "extra_in_rl": extra,
        # Set sizes after normalization, shown in the rendered verdict.
        "n_reference": len(ref),
        "n_observed": len(obs),
        # Process facts: the agent must start with the same cwd and home.
        "cwd_matches": reference.get("cwd") == observed.get("cwd"),
        "home_matches": reference.get("home") == observed.get("home"),
        # Tools whose reported version or status differ between the two listings.
        "tools_differ": sorted(
            k for k, v in (observed.get("tools") or {}).items() if (reference.get("tools") or {}).get(k) != v
        ),
        # Env names the rollout adds beyond SolSwarm's own set (never values).
        "env_only_in_rl": sorted(set(observed.get("env_keys", [])) - set(reference.get("env_keys", []))),
        # Either listing hit the walk limit, so the diff is partial.
        "truncated": bool(reference.get("truncated") or observed.get("truncated")),
    }
    # The model's own files, reported separately so they never read as drift.
    report["agent_created"] = [p for p in extra if p.startswith(MODEL_WRITABLE_ROOTS)]
    report["unexpected_extra"] = unexpected
    # The verdict is about the ENVIRONMENT, so the model's own files do not
    # make it false; they are reported separately.
    report["identical"] = not (missing or unexpected) and report["cwd_matches"] and report["home_matches"]
    return report


def render_diff(report: dict[str, Any]) -> str:
    """Human-readable tree diff (first few entries per category)."""
    head = f"sandbox tree vs SolSwarm reference: {'IDENTICAL' if report.get('identical') else 'DIFFERS'}"
    lines = [f"{head} (reference {report['n_reference']} paths, rollout {report['n_observed']})"]
    for key, label in (
        ("missing_in_rl", "in SolSwarm's sandbox but MISSING from the rollout's (defect)"),
        ("unexpected_extra", "added to the rollout's ENVIRONMENT (not model-writable)"),
        ("agent_created", "written by the agent during its session (expected)"),
    ):
        items = report.get(key) or []
        if items:
            lines.append(f"  {label} ({len(items)}):")
            lines.extend(f"    {p}" for p in items[:15])
            if len(items) > 15:
                lines.append(f"    ...and {len(items) - 15} more")
    if not report.get("cwd_matches"):
        lines.append("  cwd differs")
    if report.get("tools_differ"):
        lines.append(f"  tools differ: {', '.join(report['tools_differ'])}")
    if report.get("env_only_in_rl"):
        lines.append(f"  env names only in the rollout: {', '.join(report['env_only_in_rl'][:12])}")
    if report.get("truncated"):
        lines.append("  NOTE: a tree hit the walk limit; diff is partial")
    return "\n".join(lines)
